@extends('layouts.app')

@section('title', 'ภาพรวม · Monstopia CMS')
@section('section', 'DASHBOARD')

@section('content')
<div data-dashboard>
    <div class="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div class="mb-2 text-sm font-semibold uppercase tracking-[0.16em] text-primary">Workspace overview</div><h1 class="text-3xl font-bold tracking-tight md:text-4xl">ภาพรวมระบบ CMS</h1><p class="mt-2 max-w-2xl text-sm text-base-content/60">จัดการเนื้อหาของบริษัทให้เป็นระบบเดียว และเชื่อมต่อกับเว็บไซต์ผ่าน REST API</p></div><a href="{{ route('admin.content.create', 'projects') }}" class="btn btn-primary">เพิ่มผลงาน <span>＋</span></a></div>
    <div id="dashboard-error" class="mb-6 hidden"></div>
    <div class="stats stats-vertical mb-8 w-full border border-base-300 bg-base-100 shadow-sm sm:stats-horizontal">
        <div class="stat"><div class="stat-figure text-primary">▧</div><div class="stat-title">Projects</div><div class="stat-value text-primary" data-stat="projects"><span class="loading loading-dots loading-sm"></span></div><div class="stat-desc" data-stat="published_projects">กำลังโหลด...</div></div>
        <div class="stat"><div class="stat-figure text-secondary">▤</div><div class="stat-title">News / Articles</div><div class="stat-value text-secondary" data-stat="news"><span class="loading loading-dots loading-sm"></span></div><div class="stat-desc" data-stat="published_articles">กำลังโหลด...</div></div>
        <div class="stat"><div class="stat-figure text-accent">✦</div><div class="stat-title">Services</div><div class="stat-value text-accent" data-stat="services"><span class="loading loading-dots loading-sm"></span></div><div class="stat-desc" data-stat="active_services">กำลังโหลด...</div></div>
        <div class="stat"><div class="stat-figure text-info">♙</div><div class="stat-title">Team members</div><div class="stat-value text-info" data-stat="team_members"><span class="loading loading-dots loading-sm"></span></div><div class="stat-desc" data-stat="active_team_members">กำลังโหลด...</div></div>
    </div>
    <div class="grid gap-6 xl:grid-cols-[1.4fr_.6fr]">
        <section class="card bg-base-100"><div class="card-body"><div class="flex items-start justify-between gap-4"><div><h2 class="card-title">จัดการเนื้อหา</h2><p class="text-sm text-base-content/60">เลือก module ที่ต้องการทำงาน ข้อมูลทุกชุดถูกโหลดจาก API</p></div><span class="badge badge-outline">API driven</span></div><div class="mt-5 grid gap-3 sm:grid-cols-2"><a href="{{ route('admin.content.index', 'projects') }}" class="group rounded-xl border border-base-300 p-4 transition hover:border-primary hover:bg-primary/5"><div class="flex items-center justify-between"><span class="text-2xl text-primary">▧</span><span class="text-base-content/40 transition group-hover:text-primary">→</span></div><div class="mt-4 font-semibold">Projects</div><div class="mt-1 text-sm text-base-content/55">ผลงานและ case study ของบริษัท</div></a><a href="{{ route('admin.content.index', 'articles') }}" class="group rounded-xl border border-base-300 p-4 transition hover:border-primary hover:bg-primary/5"><div class="flex items-center justify-between"><span class="text-2xl text-secondary">▤</span><span class="text-base-content/40 transition group-hover:text-primary">→</span></div><div class="mt-4 font-semibold">Articles</div><div class="mt-1 text-sm text-base-content/55">ข่าวสารและบทความ</div></a><a href="{{ route('admin.content.index', 'services') }}" class="group rounded-xl border border-base-300 p-4 transition hover:border-primary hover:bg-primary/5"><div class="flex items-center justify-between"><span class="text-2xl text-accent">✦</span><span class="text-base-content/40 transition group-hover:text-primary">→</span></div><div class="mt-4 font-semibold">Services</div><div class="mt-1 text-sm text-base-content/55">บริการของ MONSTOPIA</div></a><a href="{{ route('admin.content.index', 'team') }}" class="group rounded-xl border border-base-300 p-4 transition hover:border-primary hover:bg-primary/5"><div class="flex items-center justify-between"><span class="text-2xl text-info">♙</span><span class="text-base-content/40 transition group-hover:text-primary">→</span></div><div class="mt-4 font-semibold">Team</div><div class="mt-1 text-sm text-base-content/55">สมาชิกและบุคลากร</div></a></div></div></section>
        <aside class="card bg-neutral text-neutral-content"><div class="card-body"><div class="text-xs font-semibold uppercase tracking-[0.16em] text-primary">System status</div><h2 class="card-title mt-2 text-white">พร้อมจัดการข้อมูล</h2><p class="text-sm leading-6 text-neutral-content/65">หน้า admin นี้เปิดเป็น shell เท่านั้น และอ่านข้อมูลด้วย fetch จาก REST API ตาม architecture ที่กำหนด</p><div class="mt-4 space-y-2 rounded-lg bg-white/5 p-3 font-mono text-xs text-neutral-content/70"><div class="flex justify-between"><span>API</span><span class="text-success">CONNECTED</span></div><div class="flex justify-between"><span>AUTH</span><span class="text-success">SESSION</span></div><div class="flex justify-between"><span>DB</span><span class="text-success">READY</span></div></div><a href="{{ url('/api/dashboard/stats') }}" target="_blank" class="btn btn-sm mt-4 border-0 bg-white/10 text-white hover:bg-white/20">เปิด dashboard JSON ↗</a></div></aside>
    </div>
</div>
@endsection
