@extends('layouts.app')

@php
    $config = [
        'projects' => ['label' => 'Project', 'thai' => 'ผลงาน', 'endpoint' => 'projects'],
        'articles' => ['label' => 'Article', 'thai' => 'ข่าวสาร', 'endpoint' => 'articles'],
        'services' => ['label' => 'Service', 'thai' => 'บริการ', 'endpoint' => 'services'],
        'team' => ['label' => 'Team member', 'thai' => 'ทีมงาน', 'endpoint' => 'team-members'],
    ][$module];
    $isEdit = $mode === 'edit';
@endphp

@section('title', ($isEdit ? 'แก้ไข' : 'เพิ่ม') . $config['thai'] . ' · Monstopia CMS')
@section('section', strtoupper($config['label']) . ' / ' . strtoupper($mode))

@section('content')
<div>
    <div class="mb-7 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div class="mb-2 text-sm font-semibold uppercase tracking-[0.16em] text-primary">{{ $config['label'] }} / {{ $mode }}</div><h1 class="text-3xl font-bold tracking-tight md:text-4xl">{{ $isEdit ? 'แก้ไข' : 'เพิ่ม' }}{{ $config['thai'] }}</h1><p class="mt-2 text-sm text-base-content/60">ฟอร์มนี้จะส่ง JSON ไปยัง <code>/api/{{ $config['endpoint'] }}</code> โดยตรง</p></div><a class="btn btn-ghost" href="{{ route('admin.content.index', $module) }}">← กลับรายการ</a></div>
    <div id="form-errors" class="mb-5 hidden"></div>
    <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
        <section class="card bg-base-100"><div class="card-body"><div data-form-loading class="mb-4 alert alert-info text-sm {{ $isEdit ? '' : 'hidden' }}"><span class="loading loading-spinner loading-sm"></span>กำลังโหลดข้อมูลเดิมจาก API...</div>
            <form data-content-form data-module="{{ $module }}" data-id="{{ $resourceId ?? '' }}" class="space-y-6">
                @csrf
                @if ($module === 'projects')
                    <div class="grid gap-5 md:grid-cols-2"><div class="form-control md:col-span-2"><label class="label" for="title"><span class="label-text">ชื่อผลงาน <span class="text-error">*</span></span></label><input class="input input-bordered" id="title" name="title" required placeholder="เช่น BullMoonJR NFT"></div><div class="form-control"><label class="label" for="slug"><span class="label-text">Slug <span class="text-error">*</span></span></label><input class="input input-bordered" id="slug" name="slug" required placeholder="bullmoonjr-nft"></div><div class="form-control"><label class="label" for="client_name"><span class="label-text">ชื่อลูกค้า / หน่วยงาน</span></label><input class="input input-bordered" id="client_name" name="client_name" placeholder="เช่น MONSTOPIA"></div><div class="form-control"><label class="label" for="project_url"><span class="label-text">Project URL</span></label><input class="input input-bordered" id="project_url" name="project_url" type="url" placeholder="https://example.com"></div><div class="form-control"><label class="label" for="image"><span class="label-text">Image URL</span></label><input class="input input-bordered" id="image" name="image" type="url" placeholder="https://cdn.example.com/project.jpg"></div><div class="form-control"><label class="label" for="category_id"><span class="label-text">หมวดหมู่</span></label><select class="select select-bordered" id="category_id" name="category_id" data-category-select><option value="">กำลังโหลด...</option></select></div><div class="form-control"><label class="label" for="status"><span class="label-text">สถานะ <span class="text-error">*</span></span></label><select class="select select-bordered" id="status" name="status" required><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></div><div class="form-control"><label class="label" for="published_at"><span class="label-text">วันที่เผยแพร่</span></label><input class="input input-bordered" id="published_at" name="published_at" type="datetime-local"></div><div class="form-control md:col-span-2"><label class="label" for="description"><span class="label-text">รายละเอียด <span class="text-error">*</span></span></label><textarea class="textarea textarea-bordered min-h-48" id="description" name="description" required placeholder="อธิบายผลงานและบทบาทของบริษัท"></textarea></div></div>
                @elseif ($module === 'articles')
                    <div class="grid gap-5 md:grid-cols-2"><div class="form-control md:col-span-2"><label class="label" for="title"><span class="label-text">หัวข้อข่าว / บทความ <span class="text-error">*</span></span></label><input class="input input-bordered" id="title" name="title" required></div><div class="form-control"><label class="label" for="slug"><span class="label-text">Slug <span class="text-error">*</span></span></label><input class="input input-bordered" id="slug" name="slug" required></div><div class="form-control"><label class="label" for="category_id"><span class="label-text">หมวดหมู่</span></label><select class="select select-bordered" id="category_id" name="category_id" data-category-select><option value="">กำลังโหลด...</option></select></div><div class="form-control md:col-span-2"><label class="label" for="summary"><span class="label-text">สรุปสั้น</span></label><textarea class="textarea textarea-bordered" id="summary" name="summary" rows="3"></textarea></div><div class="form-control"><label class="label" for="cover_image"><span class="label-text">Cover image URL</span></label><input class="input input-bordered" id="cover_image" name="cover_image" type="url"></div><div class="form-control"><label class="label" for="status"><span class="label-text">สถานะ <span class="text-error">*</span></span></label><select class="select select-bordered" id="status" name="status" required><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></div><div class="form-control"><label class="label" for="published_at"><span class="label-text">วันที่เผยแพร่</span></label><input class="input input-bordered" id="published_at" name="published_at" type="datetime-local"></div><div class="form-control md:col-span-2"><label class="label" for="content"><span class="label-text">เนื้อหา <span class="text-error">*</span></span></label><textarea class="textarea textarea-bordered min-h-72" id="content" name="content" required placeholder="เขียนเนื้อหาบทความ..."></textarea></div></div>
                @elseif ($module === 'services')
                    <div class="grid gap-5 md:grid-cols-2"><div class="form-control md:col-span-2"><label class="label" for="name"><span class="label-text">ชื่อบริการ <span class="text-error">*</span></span></label><input class="input input-bordered" id="name" name="name" required placeholder="Web Development"></div><div class="form-control"><label class="label" for="icon"><span class="label-text">Icon / identifier</span></label><input class="input input-bordered" id="icon" name="icon" placeholder="code-2"></div><div class="form-control"><label class="label" for="sort_order"><span class="label-text">ลำดับการแสดงผล <span class="text-error">*</span></span></label><input class="input input-bordered" id="sort_order" name="sort_order" type="number" min="0" value="0" required></div><div class="form-control"><label class="label" for="status"><span class="label-text">สถานะ <span class="text-error">*</span></span></label><select class="select select-bordered" id="status" name="status" required><option value="active">Active</option><option value="inactive">Inactive</option></select></div><div class="form-control md:col-span-2"><label class="label" for="description"><span class="label-text">คำอธิบาย <span class="text-error">*</span></span></label><textarea class="textarea textarea-bordered min-h-40" id="description" name="description" required></textarea></div></div>
                @else
                    <div class="grid gap-5 md:grid-cols-2"><div class="form-control"><label class="label" for="name"><span class="label-text">ชื่อ <span class="text-error">*</span></span></label><input class="input input-bordered" id="name" name="name" required></div><div class="form-control"><label class="label" for="position"><span class="label-text">ตำแหน่ง <span class="text-error">*</span></span></label><input class="input input-bordered" id="position" name="position" required></div><div class="form-control"><label class="label" for="email"><span class="label-text">อีเมล</span></label><input class="input input-bordered" id="email" name="email" type="email"></div><div class="form-control"><label class="label" for="linkedin_url"><span class="label-text">LinkedIn URL</span></label><input class="input input-bordered" id="linkedin_url" name="linkedin_url" type="url"></div><div class="form-control"><label class="label" for="profile_image"><span class="label-text">Profile image URL</span></label><input class="input input-bordered" id="profile_image" name="profile_image" type="url"></div><div class="form-control"><label class="label" for="status"><span class="label-text">สถานะ <span class="text-error">*</span></span></label><select class="select select-bordered" id="status" name="status" required><option value="active">Active</option><option value="inactive">Inactive</option></select></div><div class="form-control md:col-span-2"><label class="label" for="bio"><span class="label-text">ประวัติ / Bio</span></label><textarea class="textarea textarea-bordered min-h-40" id="bio" name="bio"></textarea></div></div>
                @endif
                <div class="flex flex-col-reverse justify-between gap-3 border-t border-base-300 pt-5 sm:flex-row sm:items-center"><span class="text-xs text-base-content/50">ข้อมูลจะถูกส่งเป็น JSON ผ่าน fetch()</span><div class="flex gap-2"><a class="btn btn-ghost" href="{{ route('admin.content.index', $module) }}">ยกเลิก</a><button class="btn btn-primary" type="submit">{{ $isEdit ? 'บันทึกการแก้ไข' : 'สร้างข้อมูล' }} <span>→</span></button></div></div>
            </form>
        </div></section>
        <aside class="card h-fit bg-neutral text-neutral-content"><div class="card-body"><div class="text-xs font-semibold uppercase tracking-[0.16em] text-primary">API contract</div><h2 class="card-title text-white">JSON first</h2><p class="text-sm leading-6 text-neutral-content/65">หน้านี้ไม่ได้ submit แบบ form POST ปกติ แต่ใช้ JavaScript เรียก endpoint พร้อม validation response จาก API</p><pre class="mt-3 overflow-x-auto rounded-lg bg-white/5 p-3 font-mono text-[11px] leading-6 text-neutral-content/70">{
  "success": true,
  "data": { ... },
  "message": "..."
}</pre></div></aside>
    </div>
</div>
@endsection
